### ISSUE TITLE
Compare links enforcing `v` tag prefix.

### ISSUE THREAD

**Issue by cliffano** [oscarotero/keep-a-changelog#10]
Hi @oscarotero ,

I'm wondering what's the reason for enforcing `v` prefix prior to the version number when generating compare link at https://github.com/oscarotero/keep-a-changelog/blob/master/src/Release.js#L149 .

```
        if (!this.version) {
            return `[Unreleased]: ${changelog.url}/compare/v${next.version}...HEAD`;
        }

        if (!this.date) {
            return `[${this.version}]: ${changelog.url}/compare/v${next.version}...HEAD`;
        }

        return `[${this.version}]: ${changelog.url}/compare/v${next.version}...v${this.version}`;
```

Could this be a keep-a-changelog or semver requirement by any chance?

My use case scenarios are a) the tag is exactly the version value, and b) the tag has a custom prefix then the version value. I'm totally fine if, for scenario b), the custom prefix has to be considered as the version.

Any thoughts on how to best tackle this?

**Comment by oscarotero** [comment]
It's a good practice to prefix the tags with 'v' to indicate that this is a version number and disambiguates the version tags with others tags. You can see some in depth explanations here:

- https://stackoverflow.com/a/21639868
- https://stackoverflow.com/a/2011372

Maybe we could add a new method to `Release` to specify a custom tag name, but not sure if this is a good idea because opens the door to random names.

**Comment by cliffano** [comment]
@oscarotero While I agree with the intention, unfortunately there are many repos out there with different tagging practices either due to legacy reason or differing opinion.
E.g.:
* Microsoft Visual Code https://github.com/Microsoft/vscode/tags uses version value as tag
* Apple Swift https://github.com/apple/swift/tags uses <prefix>-<version>-<RELEASE/SNAPSHOT>-<datestamp> format as tag
* Google GGRC https://github.com/google/ggrc-core/tags uses <version>-<FRUIT_NAME!!!> format as tag

I'm in favour of practice where it implements good practice as the default (in this case `v` prefix) but still make it configurable so that keep-a-changelog (which is a great practice of a changelog format) can be adopted by those repos which tagging standard doesn't necessarily follow the good practice.

Obviously this can be made configurable with a simple format pattern and not crazy custom function with arbitrary logic.

**Comment by oscarotero** [comment]
I understand. This can be archieved easily if you want to generate a changelog programatically. We could have something like the following:

```js
const changelog = new Changelog('My project')
    .addRelease(
        new Release('0.1.0', '2017-12-06')
            .tag('v0.1.0-gotham')
            .added('New awesome feature')
```

The problem is parsing an existing changelog file. We must parse and extract the tag names from the compare links and it's something not implemented currently.

Other option is having a way to define a tag template and use this template also in the parsing process, but this does not allow to add random names to the release. For example:

```js
const template = 'v{version}';

const changelog = new Changelog('My project');
changelog.tagNames(template);

//Parse
const fileContent = fs.readFileSync('CHANGELOG.md', 'UTF-8');
const changelog = parse(fileContent, {
    tagNames: template
});
```

**Comment by cliffano** [comment]
@oscarotero I reckon starting with the template approach would be a great improvement.
To allow random names / less-structured names, I'm thinking something like passing an array of templates (so parser checks the tags against all templates to find a match) or (god forbid) a regex.

Taking it one step at a time, having a single template would be good to start with, I'll be able to test it against a number of repos I'm dealing with right now.

**Comment by oscarotero** [comment]
Finally I added the new property `tagNameBuilder` so you can set a function to generate the tag names. Example:

```js
const changelog = parse('CHANGELOG.md');
changelog.tagNameBuilder = release => `v${release.version}-${release-date}`;
```

Let me know if this works fine before tag a new version.

**Comment by cliffano** [comment]
@oscarotero It works very well.
The tag name builder function injection is flexible enough.

Before this change: after updating the changelog with a new release, all links disappeared due to the parser not recognising the tags which don't follow the `v1.2.3` pattern.

After this change: after updating the changelog with a new release, all links are preserved and a link for the new release was added.

Thanks very much for your help. I'll definitely upgrade my deps whenever you get the chance to publish the new version.

**Comment by oscarotero** [comment]
New version released

**Comment by cliffano** [comment]
Thanks again @oscarotero
