### ISSUE TITLE
Altering Types of changes

### ISSUE THREAD

**Issue by stropho** [oscarotero/keep-a-changelog#12]
Great tool!

I understand it supports the Types of changes based on https://keepachangelog.com/en/1.0.0/
However, I think that a change of those "Types of changes" could be beneficial to many users. For example some could add a "Upgrade" type or anything else...
Well, it was discussed a while back here https://github.com/brightcove/kacl/issues/6 But with no additional initiative it seems...

Is this something that would be considered?

Solution proposals:
1. probably the easiest: don't change implementation. the `Release` class can be extended. Just cover it by a test and mention in documentation, so people can rely on it.
2. based on point 1. - Have an Additional class `ReleaseBase` that could e.g. accept another parameter in constructor to define the types. Additionaly, `ReleaseBase` does not include methods like `added`, `changed` etc. `Release` class would extend `ReleaseBase` . It still doesn't introduce any breaking changes.
3. Change the current `Release` class to accept optional parameter for types (in constructor). No way to add new methods for specific change types.
4. Have an additional method in `Release` class `setTypes`. That just doesn't seem right

**Comment by oscarotero** [comment]
I think, for now, the proposal 1 is the best, because it's pretty easy to extend the changes with more types. Just note that currently there's a function for each type (`added()`, `changed()` ...) so I would not replace the current types, for backward compatibility, just add more different types).

Other problem I see is the parser, that needs a way to set a custom `Release` class to create the instance here: https://github.com/oscarotero/keep-a-changelog/blob/master/src/parser.js#L28

**Comment by stropho** [comment]
Good point. Haven't noticed that thing with the parser.

The only quick fix I can think of now is a bit of Dependency Injection:
```js
function defaultReleaseCreator(title, description){ return new Realease(title, description)}
function parser(markdown, releaseCreator = defaultReleaseCreator) {
//...
}
```

**Comment by oscarotero** [comment]
I think that an object with options (so it can be extended in a future with more settings) is better. For example:

```js
const options = {
    releaseCreator: (title, description) => new Release(title, description)
}

const changelog = parser(markdown, options);
```

If you want to work on a PR for this, I'd appreciate it very much.

**Comment by stropho** [comment]
I'm on it :wink:

**Comment by stropho** [comment]
https://github.com/oscarotero/keep-a-changelog/pull/13
