### ISSUE TITLE
Option to fail the changelog command if parsing fails

### ISSUE THREAD

**Issue by dekpient** [oscarotero/keep-a-changelog#14]
Hi! Thanks for this tool.

We're using the `changelog` command to ensure our CHANGELOG.md is formatted properly. At the moment, if the file cannot be parsed, it just prints out the error in red. It'd be nice to have an option so it exits with non-zero code. That way we can run the command as part of our CI builds.

I'm good to contribute if you're happy with the idea.

Cheers!

**Comment by oscarotero** [comment]
Yes, it's a good idea. Maybe a `--quiet` option or something like that.

I'm happy with your pull request, thanks!
