### ISSUE TITLE
Newline after headings

### ISSUE THREAD

**Issue by mitar** [oscarotero/keep-a-changelog#22]
I prefer to have newline after headings, but this package removes one. Could that be an option to keep or even enforce?

**Comment by oscarotero** [comment]
I wouldn't like to complicate this with formatting options.

**Comment by MattiSG** [comment]
This issue seems to be a specific case of https://github.com/oscarotero/keep-a-changelog/issues/28.

**Comment by oscarotero** [comment]
In 2.2.0 you can configure the output format to `markdownlint`, that add a new line after every heading.
