### ISSUE TITLE
Quality of life

### ISSUE THREAD

**Issue by ThatGuyJamal** [oscarotero/keep-a-changelog#24]
Hello, I recently found this project today, and it was really helpful in my O.S.S projects with Deno, thanks.

However, when installing it I did find some bugs.

The first one is the Deno URL. It should be `https://deno.land/x/changelog@v2.0.0/mod.ts` but it has a typo in the readme. it's missing the `v` in the version number.

The second thing is not a bug but more of a request. Could you please change the access modifiers on some of the classes to private? Its hard to tell which ones are usage functions vs variables. 

Example:
```ts
export default class Release {
  changelog?: Changelog;
  version?: Semver;
  date?: Date;
  description: string;
  changes: Map<string, Change[]>;
 }
 All these methods can be assessed for no reason and other util functions on the class. It would make it more simple to script the change logs if some were set to private or protected, thanks.

**Comment by oscarotero** [comment]
Sorry for the late reply.
I've fixed the wrong urls in the README file, thanks.
Regarding to the second thing, some of these properties must be edited externally, so they cannot be private.
Maybe Deno docs can help you. For example: https://doc.deno.land/https://deno.land/x/changelog@v2.0.1/src/Release.ts/~/default
