### ISSUE TITLE
Support yanked releases

### ISSUE THREAD

**Issue by FayneAldan** [oscarotero/keep-a-changelog#25]
The parsing fails to parse "yanked" releases:
https://github.com/FayneAldan/SVRichPresence/blob/80996477c83571a163b74d37fe778579f3f40f3b/CHANGELOG.md?plain=1#L110
> Parse error in the line 111: Syntax error in the release title

There's also no way to add a yanked release in the API.

Yanked releases are mentioned in the Keep a Changelog FAQ.
![](https://files.catbox.moe/gj89qb.png)

**Comment by oscarotero** [comment]
Added in v2.1.0. Thanks for bringing it up.
