### ISSUE TITLE
`setYanked` in `Release` class

### ISSUE THREAD

**Issue by FayneAldan** [oscarotero/keep-a-changelog#26]
There should be a method in the `Release` class to set the release as "Yanked"

**Comment by FayneAldan** [comment]
I'm thinking maybe the command could just be `yank` for simplicity and can take an optional boolean value that defaults to true?

**Comment by oscarotero** [comment]
Yes, maybe. For now you can simply set `release.yanked = true`.
In next version I'll add this method.

**Comment by oscarotero** [comment]
added in 2.2.0
