### ISSUE TITLE
Unnecessary newline added near top by `changelog` command

### ISSUE THREAD

**Issue by FayneAldan** [oscarotero/keep-a-changelog#27]
The `changelog` command seems to add a non-standard newline near the top of the CHANGELOG file below `# Changelog`.
![](https://files.catbox.moe/dv4nxa.png)

**Comment by oscarotero** [comment]
Yes, good point. I'll fix it.

**Comment by MattiSG** [comment]
This seems contrary to https://github.com/oscarotero/keep-a-changelog/issues/28.

**Comment by oscarotero** [comment]
fixed in 2.2.0
