### ISSUE TITLE
Follow `markdownlint` rules

### ISSUE THREAD

**Issue by Ndpnt** [oscarotero/keep-a-changelog#28]
Hi,

Thanks for this useful tool to generate changelog.

Could you modify the generated markdown to follow the rules defined by [`markdownlint`](https://github.com/DavidAnson/markdownlint) to enforce consistency in Markdown files.

Currently the two rules that are not respected are:
- [Lists should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/v0.26.2/doc/Rules.md#md032)
- [Headings should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/v0.26.2/doc/Rules.md#md022)

**Comment by oscarotero** [comment]
Hi, @Ndpnt and @MattiSG 

Thanks for your contribution. Yes, this project is actively maintained.

I can see the benefits of following the markdownlint rules, but I'd like have it as an optional feature. There are many people that prefer the original compact version. What do you think about something like this?:

```js
const string = changelog.toString({ markdownlint: true });
```

**Comment by oscarotero** [comment]
The problem with this is it will change all existing markdowns and force to people already using this library to configure it to back to the expected compact version.
It would be a breaking change, so maybe in the future 3.x version this can be enabled by default, but for now I think it would be nice to have this option disabled to release the version 2.2.0.

**Comment by oscarotero** [comment]
I'd like to have it also in 2.x version, but as a configurable option.

If you don't want to configure the library, another option is a static property, like `Changelog.format = "markdownlint"`, so it's set once and applied always.

**Comment by Ndpnt** [comment]
I was just in favor of enforcing standards by default but It's OK to configure the library.
I think it's best to have both options: a `toString` method option and also a static property.

**Comment by Ndpnt** [comment]
I'm not really familiar with your codebase and I think it will be much easier and quicker for you to make the changes and to create the associated documentation, so I'd really appreciate it if you could handle the changes, if not I will.

**Comment by oscarotero** [comment]
Okay, no problem. I'll work on that

**Comment by Ndpnt** [comment]
Thanks! 🙏

**Comment by oscarotero** [comment]
Done. I've released 2.2.0 with the `format` option.

**Comment by janhalama** [comment]
> Done. I've released 2.2.0 with the format option.

Thanks for the release, can you also publish it on npm registry. It is not published yet: https://www.npmjs.com/package/keep-a-changelog

**Comment by oscarotero** [comment]
Ops, sorry. I thought it was published automatically. 
Done!
