### ISSUE TITLE
Laxer parsing of release description

### ISSUE THREAD

**Issue by Glandos** [oscarotero/keep-a-changelog#30]
Currently, the following entry fails to parse:
```markdown
## [Unreleased]
This is a brand new releases with:
- Configuration is now done within the Web client, for authorized users.
### Added
- New configuration screen
```
It seems that the description can only be a `<p>` tag as parsed. Could it be anything before the first matching change type?

**Comment by oscarotero** [comment]
Mmm, ok. For now only paragraphs are allowed (https://github.com/oscarotero/keep-a-changelog/blob/master/src/parser.ts#L68). I'll change that.
Thanks!

**Comment by oscarotero** [comment]
Done and released in https://github.com/oscarotero/keep-a-changelog/releases/tag/v2.2.1
