### ISSUE TITLE
wrong versions

### ISSUE THREAD

**Issue by wareczek** [oscarotero/keep-a-changelog#34]
Hi @oscarotero. Aren't the following versions in the changelog bad?
https://github.com/oscarotero/keep-a-changelog/blob/master/CHANGELOG.md?plain=1#L9-L15
They should be 2.4.0 and 2.4.1, not 3.4.0 and 3.4.1 ;) To npm you pushed version 2.4.1.

**Comment by oscarotero** [comment]
OMG, you're right!
I just fixed it. Thanks for the heads up.
